services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=appy-database'
      - 'MYSQL_ROOT_PASSWORD=passwd'
    ports:
      - '3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80:80
    environment:
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: ''
